package mmc.warehousemanagementsystem.entity;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Thu Sep 08 04:27:07 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.material_id
     *
     * @mbg.generated Thu Sep 08 04:27:07 CST 2022
     */
    private Long materialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.quantity
     *
     * @mbg.generated Thu Sep 08 04:27:07 CST 2022
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.admin_id
     *
     * @mbg.generated Thu Sep 08 04:27:07 CST 2022
     */
    private Long adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.type
     *
     * @mbg.generated Thu Sep 08 04:27:07 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.gmt_created
     *
     * @mbg.generated Thu Sep 08 04:27:07 CST 2022
     */
    private Long gmtCreated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Thu Sep 08 04:27:07 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated Thu Sep 08 04:27:07 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.material_id
     *
     * @return the value of orders.material_id
     *
     * @mbg.generated Thu Sep 08 04:27:07 CST 2022
     */
    public Long getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.material_id
     *
     * @param materialId the value for orders.material_id
     *
     * @mbg.generated Thu Sep 08 04:27:07 CST 2022
     */
    public void setMaterialId(Long materialId) {
        this.materialId = materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.quantity
     *
     * @return the value of orders.quantity
     *
     * @mbg.generated Thu Sep 08 04:27:07 CST 2022
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.quantity
     *
     * @param quantity the value for orders.quantity
     *
     * @mbg.generated Thu Sep 08 04:27:07 CST 2022
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.admin_id
     *
     * @return the value of orders.admin_id
     *
     * @mbg.generated Thu Sep 08 04:27:07 CST 2022
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.admin_id
     *
     * @param adminId the value for orders.admin_id
     *
     * @mbg.generated Thu Sep 08 04:27:07 CST 2022
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.type
     *
     * @return the value of orders.type
     *
     * @mbg.generated Thu Sep 08 04:27:07 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.type
     *
     * @param type the value for orders.type
     *
     * @mbg.generated Thu Sep 08 04:27:07 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.gmt_created
     *
     * @return the value of orders.gmt_created
     *
     * @mbg.generated Thu Sep 08 04:27:07 CST 2022
     */
    public Long getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.gmt_created
     *
     * @param gmtCreated the value for orders.gmt_created
     *
     * @mbg.generated Thu Sep 08 04:27:07 CST 2022
     */
    public void setGmtCreated(Long gmtCreated) {
        this.gmtCreated = gmtCreated;
    }
}